import { Router } from 'express';
import fs from 'node:fs';
import path from 'node:path';
import mongoose from 'mongoose';
import multer from 'multer';
import { Meeting } from '../models/Meeting.js';
import { requireAuth, signMediaToken } from '../middleware/auth.js';
import { HttpError, clampInt, escapeRegex } from '../utils/http.js';
import { exportFormats, renderExport } from '../utils/export.js';
import { config } from '../config.js';
import { cancel, enqueue, isActive, whisperStatus } from '../services/transcription.js';
import { answer, loadAiSettings, summarize } from '../services/ai.js';

const router = Router();
router.use(requireAuth);

const { ObjectId } = mongoose.Types;

function ownedFilter(req) {
  if (!mongoose.isValidObjectId(req.params.id)) throw new HttpError(404, 'Meeting not found');
  return { _id: req.params.id, user: req.userId };
}

async function findOwned(req, projection) {
  const meeting = await Meeting.findOne(ownedFilter(req), projection);
  if (!meeting) throw new HttpError(404, 'Meeting not found');
  return meeting;
}

const str = (v, max) => String(v ?? '').trim().slice(0, max);

function cleanSegment(raw) {
  const text = str(raw?.text, 10000);
  const startMs = Math.max(0, Math.round(Number(raw?.startMs) || 0));
  const endMs = Math.max(startMs, Math.round(Number(raw?.endMs) || startMs));
  if (!text) return null;
  return {
    _id: new ObjectId(),
    startMs,
    endMs,
    text,
    speaker: str(raw?.speaker, 60) || 'Speaker 1',
    highlighted: Boolean(raw?.highlighted),
  };
}

function cleanTags(tags) {
  if (!Array.isArray(tags)) throw new HttpError(400, 'tags must be an array');
  return [...new Set(tags.map((t) => str(t, 40).toLowerCase()).filter(Boolean))].slice(0, 30);
}

// Transcript edits are locked while Whisper is rewriting it.
async function assertEditable(req) {
  const meeting = await findOwned(req, { 'transcription.status': 1 });
  if (isActive(meeting.transcription?.status)) {
    throw new HttpError(409, 'The transcript is being regenerated by Whisper. Try again when it finishes.');
  }
}

const removeFile = (filename) =>
  filename && fs.promises.unlink(path.join(config.uploadDir, filename)).catch(() => {});

// ---------- list / create ----------

router.get('/', async (req, res) => {
  const q = str(req.query.q, 200);
  const page = clampInt(req.query.page, 1, 10000, 1);
  const limit = clampInt(req.query.limit, 1, 50, 20);

  const match = { user: new ObjectId(req.userId) };
  let previewSource = { $slice: ['$segments', 1] };
  if (q) {
    const rx = new RegExp(escapeRegex(q), 'i');
    match.$or = [{ title: rx }, { notes: rx }, { tags: rx }, { 'segments.text': rx }];
    previewSource = {
      $filter: {
        input: '$segments',
        cond: { $regexMatch: { input: '$$this.text', regex: escapeRegex(q), options: 'i' } },
        limit: 1,
      },
    };
  }

  const [items, total] = await Promise.all([
    Meeting.aggregate([
      { $match: match },
      { $sort: { createdAt: -1 } },
      { $skip: (page - 1) * limit },
      { $limit: limit },
      {
        $project: {
          title: 1,
          status: 1,
          tags: 1,
          language: 1,
          durationMs: 1,
          startedAt: 1,
          createdAt: 1,
          hasAudio: { $cond: [{ $ifNull: ['$audio.filename', false] }, true, false] },
          transcription: { status: 1, progress: 1, source: 1 },
          segmentCount: { $size: '$segments' },
          preview: { $first: previewSource },
        },
      },
      {
        $addFields: {
          preview: { $substrCP: [{ $ifNull: ['$preview.text', ''] }, 0, 240] },
        },
      },
    ]),
    Meeting.countDocuments(match),
  ]);

  res.json({ items, total, page, pages: Math.max(1, Math.ceil(total / limit)) });
});

router.post('/', async (req, res) => {
  const meeting = await Meeting.create({
    user: req.userId,
    title: str(req.body?.title, 200) || `Meeting ${new Date().toLocaleString('en-US')}`,
    language: str(req.body?.language, 20) || 'en-US',
    startedAt: req.body?.startedAt ? new Date(req.body.startedAt) : new Date(),
    tags: req.body?.tags ? cleanTags(req.body.tags) : [],
  });
  res.status(201).json({ meeting });
});

// ---------- single meeting ----------

router.get('/:id', async (req, res) => {
  res.json({ meeting: await findOwned(req) });
});

router.patch('/:id', async (req, res) => {
  const b = req.body || {};
  const $set = {};
  if ('title' in b) {
    $set.title = str(b.title, 200);
    if (!$set.title) throw new HttpError(400, 'Title cannot be empty');
  }
  if ('notes' in b) $set.notes = String(b.notes ?? '').slice(0, 50000);
  if ('tags' in b) $set.tags = cleanTags(b.tags);
  if ('language' in b) $set.language = str(b.language, 20);
  if ('status' in b) {
    if (!['recording', 'completed'].includes(b.status)) throw new HttpError(400, 'Invalid status');
    $set.status = b.status;
  }
  if ('durationMs' in b) $set.durationMs = Math.max(0, Math.round(Number(b.durationMs) || 0));
  if ('endedAt' in b) $set.endedAt = b.endedAt ? new Date(b.endedAt) : null;

  const meeting = await Meeting.findOneAndUpdate(ownedFilter(req), { $set }, { returnDocument: 'after', runValidators: true });
  if (!meeting) throw new HttpError(404, 'Meeting not found');
  res.json({ meeting });
});

router.delete('/:id', async (req, res) => {
  const meeting = await findOwned(req, { audio: 1, tracks: 1 });
  await cancel(meeting._id);
  await meeting.deleteOne();
  removeFile(meeting.audio?.filename);
  removeFile(meeting.tracks?.filename);
  res.status(204).end();
});

// ---------- segments ----------

router.post('/:id/segments', async (req, res) => {
  const raw = req.body?.segments;
  if (!Array.isArray(raw) || raw.length === 0) throw new HttpError(400, 'segments must be a non-empty array');
  if (raw.length > 500) throw new HttpError(400, 'Too many segments in one request (max 500)');
  await assertEditable(req);
  const segments = raw.map(cleanSegment).filter(Boolean);
  if (!segments.length) return res.status(201).json({ segments: [] });

  const result = await Meeting.updateOne(ownedFilter(req), {
    $push: { segments: { $each: segments, $sort: { startMs: 1 } } },
  });
  if (!result.matchedCount) throw new HttpError(404, 'Meeting not found');
  res.status(201).json({ segments });
});

router.patch('/:id/segments/:segId', async (req, res) => {
  if (!mongoose.isValidObjectId(req.params.segId)) throw new HttpError(404, 'Segment not found');
  await assertEditable(req);
  const b = req.body || {};
  const $set = {};
  if ('text' in b) {
    const text = str(b.text, 10000);
    if (!text) throw new HttpError(400, 'Text cannot be empty (delete the segment instead)');
    $set['segments.$.text'] = text;
  }
  if ('speaker' in b) $set['segments.$.speaker'] = str(b.speaker, 60) || 'Speaker 1';
  if ('highlighted' in b) $set['segments.$.highlighted'] = Boolean(b.highlighted);

  const meeting = await Meeting.findOneAndUpdate(
    { ...ownedFilter(req), 'segments._id': req.params.segId },
    { $set },
    { returnDocument: 'after', projection: { segments: { $elemMatch: { _id: req.params.segId } } } },
  );
  if (!meeting) throw new HttpError(404, 'Segment not found');
  res.json({ segment: meeting.segments[0] });
});

router.delete('/:id/segments/:segId', async (req, res) => {
  if (!mongoose.isValidObjectId(req.params.segId)) throw new HttpError(404, 'Segment not found');
  await assertEditable(req);
  const result = await Meeting.updateOne(ownedFilter(req), { $pull: { segments: { _id: req.params.segId } } });
  if (!result.matchedCount) throw new HttpError(404, 'Meeting not found');
  res.status(204).end();
});

router.patch('/:id/speakers', async (req, res) => {
  const from = str(req.body?.from, 60);
  const to = str(req.body?.to, 60);
  if (!from || !to) throw new HttpError(400, 'Both "from" and "to" are required');
  await assertEditable(req);
  const result = await Meeting.updateOne(
    ownedFilter(req),
    { $set: { 'segments.$[s].speaker': to } },
    { arrayFilters: [{ 's.speaker': from }] },
  );
  if (!result.matchedCount) throw new HttpError(404, 'Meeting not found');
  res.json({ meeting: await findOwned(req) });
});

// ---------- audio ----------

fs.mkdirSync(config.uploadDir, { recursive: true });

const EXT = {
  'audio/webm': 'webm', 'video/webm': 'webm', 'audio/ogg': 'ogg', 'audio/mp4': 'm4a', 'audio/x-m4a': 'm4a',
  'audio/mpeg': 'mp3', 'audio/wav': 'wav', 'audio/x-wav': 'wav', 'audio/wave': 'wav', 'audio/flac': 'flac',
  'audio/aac': 'aac', 'video/mp4': 'mp4', 'video/quicktime': 'mov',
};
const KNOWN_EXT = new Set(Object.values(EXT));

const upload = multer({
  storage: multer.diskStorage({
    destination: config.uploadDir,
    filename: (req, file, cb) => {
      const fromName = path.extname(file.originalname || '').slice(1).toLowerCase();
      const ext = EXT[file.mimetype.split(';')[0]] || (KNOWN_EXT.has(fromName) ? fromName : 'bin');
      cb(null, `${req.params.id}-${file.fieldname}-${Date.now()}.${ext}`);
    },
  }),
  limits: { fileSize: config.maxUploadMb * 1024 * 1024, files: 2 },
  fileFilter: (_req, file, cb) => {
    const ok = file.mimetype.startsWith('audio/') || file.mimetype.startsWith('video/');
    cb(ok ? null : new HttpError(415, 'Only audio or video files are accepted'), ok);
  },
});

const fileInfo = (f) => ({ filename: f.filename, mimeType: f.mimetype.split(';')[0], size: f.size });

// Fields: "audio" (required, used for playback) and optional "tracks"
// (stereo: left = mic, right = tab audio) used for per-speaker Whisper transcription.
router.post(
  '/:id/audio',
  async (req, _res, next) => {
    req.meeting = await findOwned(req, { audio: 1, tracks: 1, transcription: 1 });
    next();
  },
  upload.fields([{ name: 'audio', maxCount: 1 }, { name: 'tracks', maxCount: 1 }]),
  async (req, res) => {
    const audio = req.files?.audio?.[0];
    const tracks = req.files?.tracks?.[0];
    if (!audio) {
      removeFile(tracks?.filename);
      throw new HttpError(400, 'No audio file received (field name must be "audio")');
    }
    await cancel(req.meeting._id); // a new recording supersedes any running job
    const update = tracks
      ? { $set: { audio: fileInfo(audio), tracks: fileInfo(tracks) } }
      : { $set: { audio: fileInfo(audio) }, $unset: { tracks: 1 } };
    await Meeting.updateOne(ownedFilter(req), update);
    removeFile(req.meeting.audio?.filename);
    removeFile(req.meeting.tracks?.filename);

    const transcribe = req.query.transcribe !== 'false' && whisperStatus().available && whisperStatus().auto;
    if (transcribe) await enqueue(req.meeting._id);
    res.status(201).json({ meeting: await findOwned(req) });
  },
);

// ---------- whisper ----------

router.post('/:id/transcribe', async (req, res) => {
  if (!whisperStatus().available) throw new HttpError(503, 'Local Whisper is not installed on the server');
  const meeting = await findOwned(req, { audio: 1, transcription: 1 });
  if (!meeting.audio?.filename) throw new HttpError(400, 'This meeting has no audio to transcribe');
  if (!(await enqueue(meeting._id))) throw new HttpError(409, 'Transcription is already in progress');
  res.status(202).json({ meeting: await findOwned(req) });
});

router.delete('/:id/transcribe', async (req, res) => {
  const meeting = await findOwned(req, { _id: 1 });
  await cancel(meeting._id);
  res.json({ meeting: await findOwned(req) });
});

router.get('/:id/audio-url', async (req, res) => {
  const meeting = await findOwned(req, { audio: 1 });
  if (!meeting.audio?.filename) throw new HttpError(404, 'This meeting has no audio');
  res.json({ url: `/api/media/${meeting._id}?token=${signMediaToken(req.userId, meeting._id)}` });
});

// ---------- AI (summary + Q&A) ----------

// Only one AI request per meeting at a time, so double clicks don't pay twice.
const aiBusy = new Set();
async function withAiLock(id, fn) {
  if (aiBusy.has(id)) throw new HttpError(409, 'An AI request for this meeting is already running.');
  aiBusy.add(id);
  try {
    return await fn();
  } finally {
    aiBusy.delete(id);
  }
}

router.post('/:id/summary', async (req, res) => {
  const meeting = await findOwned(req, { title: 1, notes: 1, startedAt: 1, createdAt: 1, durationMs: 1, segments: 1 });
  const settings = await loadAiSettings(req.userId);
  const text = await withAiLock(String(meeting._id), () => summarize(meeting, settings));
  const summary = { text, generatedAt: new Date(), provider: 'openai', model: settings.model };
  await Meeting.updateOne(ownedFilter(req), { $set: { summary } });
  res.json({ summary });
});

router.delete('/:id/summary', async (req, res) => {
  await Meeting.updateOne(ownedFilter(req), { $unset: { summary: 1 } });
  res.status(204).end();
});

router.post('/:id/chat', async (req, res) => {
  const question = str(req.body?.question, 4000);
  if (!question) throw new HttpError(400, 'Ask a question');
  const meeting = await findOwned(req, {
    title: 1, notes: 1, startedAt: 1, createdAt: 1, durationMs: 1, segments: 1, summary: 1, chat: 1,
  });
  const settings = await loadAiSettings(req.userId);
  const reply = await withAiLock(String(meeting._id), () => answer(meeting, meeting.chat, question, settings));
  const added = [
    { _id: new ObjectId(), role: 'user', content: question, at: new Date() },
    { _id: new ObjectId(), role: 'assistant', content: reply.slice(0, 20000), at: new Date() },
  ];
  await Meeting.updateOne(ownedFilter(req), { $push: { chat: { $each: added } } });
  res.json({ messages: added });
});

router.delete('/:id/chat', async (req, res) => {
  await Meeting.updateOne(ownedFilter(req), { $set: { chat: [] } });
  res.status(204).end();
});

// ---------- export ----------

router.get('/:id/export', async (req, res) => {
  const format = String(req.query.format || 'txt').toLowerCase();
  if (!exportFormats.includes(format)) throw new HttpError(400, `format must be one of: ${exportFormats.join(', ')}`);
  const meeting = (await findOwned(req)).toObject();
  const { body, mime, filename } = renderExport(meeting, format);
  res.attachment(filename).type(`${mime}; charset=utf-8`).send(body);
});

export default router;
